Simplify UTC timestamp migration, run as single statement transactions
NYPL-Simplified/server_core pull request #1259
Opened 2021-05-25 20:45 UTC by nballenger

I've changed two things:

1. I set the `migration/20210405-update-datetime-columns.sql` file up to use one `ALTER` per table, and removed the `UPDATE` statements because the conversion is actually accomplished during the table alteration.
2. I added some logic to `scripts.py` in the `DatabaseMigrationScript` class, aimed at running individual statements in a migration file within their own transactions. That only triggers if somewhere in the .sql file the string `SIMPLYE_MIGRATION_TRANSACTION_PER_STATEMENT` appears.

I don't have the circ manager set up locally in a way that makes this easy to test, so anything you spot would be good to know about before I build this and try it on QA.

2021-05-25 20:57 UTC, leonardr approved these changes
The code makes sense. Tomorrow I'll spend some time setting up a database that needs this migration, and make sure the SQL works. I can't test the performance characteristics though.

2021-05-25 23:07 UTC, nballenger commented
Thanks--I think as long as it runs successfully that's fine, we'll just have to see how it fares at scale on the QA db.

2021-05-26 13:40 UTC, leonardr commented on scripts.py
> +    def _extract_statements_from_sql_file(filepath):
This is missing its `self`.

2021-05-26 13:41 UTC, leonardr requested changes
While running this for real I found a minor syntax error. After fixing it, the migration ran and I ran spot checks to verify that the fields were actually migrated.

2021-05-26 14:07 UTC, leonardr approved these changes

2021-05-26 14:08 UTC, merged